#!/bin/bash

echo "library directory: ${FOAM_USER_LIBBIN}"


echo -n "compiling mySolidSpecie ... "
wmake mySolidSpecie  &>> log.Allwmake
echo "done!"

echo -n "compiling myReactionThermo ... "
wmake myReactionThermo &>> log.Allwmake
echo "done!"


echo -n "compiling mySolidThermo ... "
wmake mySolidThermo &>> log.Allwmake
echo "done!"

echo -n "compiling mySolidChemistryModel ... "
wmake mySolidChemistryModel  &>> log.Allwmake
echo "done!"

grep -q "error" log.Allwmake && echo -n " Error Found" || echo "Error Not Found"
